apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
  project: roboshop
spec:
 containers:
  - name: nginx
    image: nginx
 nodeSelector: #which is used to select our creeated label with this project: roboshop1 to the node
    project: roboshop