apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      # 1. Hard Rule: Must be in US-East-1
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1b
            - us-east-1c
      
      # 2. Soft Rule: Prefer based on weight and with 1b&1c zones both satisfies,based on that weight it will select
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        preference:
          matchExpressions:
          - key:  topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1b
      - weight: 100
        preference:
          matchExpressions:
          - key:  topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1c
  containers:
  - name: nginx
    image: nginx:latest