apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      # 1. Hard Rule: Must be in US-East-1
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1a
            - us-east-1d
      
      # # 2. Soft Rule: Prefer SSD nodes, but bypass if unavailable
      # preferredDuringSchedulingIgnoredDuringExecution:
      # - weight: 80
      #   preference:
      #     matchExpressions:
      #     - key: disktype
      #       operator: In
      #       values:
      #       - ssd
  containers:
  - name: nginx
    image: nginx:latest